---
- name: install nginx
  apt: name=nginx state=present

- name: nginx server status
  service: name=nginx state=started enabled=yes

- name: change nginx config for default vhost
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0755
  notify: restart nginx

- name: add index.php to see SERVER_IP
  copy:
    src: index.php
    dest: /var/www/html/index.php
    owner: root
    group: root
    mode: 0755

- name: delete index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: install PHP FPM
  apt: name={{ item }} state=present
  with_items:
    - php-fpm
    - php-mysql

- name: php-fpm status
  service: name=php7.0-fpm state=started enabled=yes

