---
- name: install mysql
  apt: name=mysql-server state=present

- name: mysql server status
  service: name=mysql state=started enabled=yes

- name: change nginx config for default vhost
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0755
  notify: restart mysql
