---
- name: common software and configuration
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common
    - fail2ban
    - security

- name: install webserver
  hosts: webservers
  become: yes
  become_method: sudo
  roles:
    - webserver

- name: install mysql
  hosts: dbservers
  become: yes
  become_method: sudo
  roles:
    - db

- name: install elastic
  hosts: elastic
  become: yes
  become_method: sudo
  roles:
    - elastic
  


